language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.14"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

# fix https://github.com/miyagawa/cpanminus/issues/412    
before_install:
    - cpanm -nq Pod::Readme

install:
    - cpanm --quiet --notest --skip-satisfied Dist::Milla
    - cpanm --installdeps .

# full release test
script:
    - milla smoke --release --author

# normal tests and report test coverage to coveralls.io
after_success:
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
    - perl Build.PL && ./Build build && cover -test -report coveralls
